version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - TZ=Asia/Tokyo
    command: sleep infinity
