// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aki-13627/animalia/backend-go/ent/blockrelation"
	"github.com/aki-13627/animalia/backend-go/ent/predicate"
)

// BlockRelationDelete is the builder for deleting a BlockRelation entity.
type BlockRelationDelete struct {
	config
	hooks    []Hook
	mutation *BlockRelationMutation
}

// Where appends a list predicates to the BlockRelationDelete builder.
func (brd *BlockRelationDelete) Where(ps ...predicate.BlockRelation) *BlockRelationDelete {
	brd.mutation.Where(ps...)
	return brd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (brd *BlockRelationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, brd.sqlExec, brd.mutation, brd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (brd *BlockRelationDelete) ExecX(ctx context.Context) int {
	n, err := brd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (brd *BlockRelationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(blockrelation.Table, sqlgraph.NewFieldSpec(blockrelation.FieldID, field.TypeUUID))
	if ps := brd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, brd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	brd.mutation.done = true
	return affected, err
}

// BlockRelationDeleteOne is the builder for deleting a single BlockRelation entity.
type BlockRelationDeleteOne struct {
	brd *BlockRelationDelete
}

// Where appends a list predicates to the BlockRelationDelete builder.
func (brdo *BlockRelationDeleteOne) Where(ps ...predicate.BlockRelation) *BlockRelationDeleteOne {
	brdo.brd.mutation.Where(ps...)
	return brdo
}

// Exec executes the deletion query.
func (brdo *BlockRelationDeleteOne) Exec(ctx context.Context) error {
	n, err := brdo.brd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{blockrelation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (brdo *BlockRelationDeleteOne) ExecX(ctx context.Context) {
	if err := brdo.Exec(ctx); err != nil {
		panic(err)
	}
}
