// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aki-13627/animalia/backend-go/ent/blockrelation"
	"github.com/aki-13627/animalia/backend-go/ent/predicate"
	"github.com/aki-13627/animalia/backend-go/ent/user"
	"github.com/google/uuid"
)

// BlockRelationQuery is the builder for querying BlockRelation entities.
type BlockRelationQuery struct {
	config
	ctx        *QueryContext
	order      []blockrelation.OrderOption
	inters     []Interceptor
	predicates []predicate.BlockRelation
	withFrom   *UserQuery
	withTo     *UserQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BlockRelationQuery builder.
func (brq *BlockRelationQuery) Where(ps ...predicate.BlockRelation) *BlockRelationQuery {
	brq.predicates = append(brq.predicates, ps...)
	return brq
}

// Limit the number of records to be returned by this query.
func (brq *BlockRelationQuery) Limit(limit int) *BlockRelationQuery {
	brq.ctx.Limit = &limit
	return brq
}

// Offset to start from.
func (brq *BlockRelationQuery) Offset(offset int) *BlockRelationQuery {
	brq.ctx.Offset = &offset
	return brq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (brq *BlockRelationQuery) Unique(unique bool) *BlockRelationQuery {
	brq.ctx.Unique = &unique
	return brq
}

// Order specifies how the records should be ordered.
func (brq *BlockRelationQuery) Order(o ...blockrelation.OrderOption) *BlockRelationQuery {
	brq.order = append(brq.order, o...)
	return brq
}

// QueryFrom chains the current query on the "from" edge.
func (brq *BlockRelationQuery) QueryFrom() *UserQuery {
	query := (&UserClient{config: brq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := brq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := brq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(blockrelation.Table, blockrelation.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, blockrelation.FromTable, blockrelation.FromColumn),
		)
		fromU = sqlgraph.SetNeighbors(brq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTo chains the current query on the "to" edge.
func (brq *BlockRelationQuery) QueryTo() *UserQuery {
	query := (&UserClient{config: brq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := brq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := brq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(blockrelation.Table, blockrelation.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, blockrelation.ToTable, blockrelation.ToColumn),
		)
		fromU = sqlgraph.SetNeighbors(brq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BlockRelation entity from the query.
// Returns a *NotFoundError when no BlockRelation was found.
func (brq *BlockRelationQuery) First(ctx context.Context) (*BlockRelation, error) {
	nodes, err := brq.Limit(1).All(setContextOp(ctx, brq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{blockrelation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (brq *BlockRelationQuery) FirstX(ctx context.Context) *BlockRelation {
	node, err := brq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BlockRelation ID from the query.
// Returns a *NotFoundError when no BlockRelation ID was found.
func (brq *BlockRelationQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = brq.Limit(1).IDs(setContextOp(ctx, brq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{blockrelation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (brq *BlockRelationQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := brq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BlockRelation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BlockRelation entity is found.
// Returns a *NotFoundError when no BlockRelation entities are found.
func (brq *BlockRelationQuery) Only(ctx context.Context) (*BlockRelation, error) {
	nodes, err := brq.Limit(2).All(setContextOp(ctx, brq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{blockrelation.Label}
	default:
		return nil, &NotSingularError{blockrelation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (brq *BlockRelationQuery) OnlyX(ctx context.Context) *BlockRelation {
	node, err := brq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BlockRelation ID in the query.
// Returns a *NotSingularError when more than one BlockRelation ID is found.
// Returns a *NotFoundError when no entities are found.
func (brq *BlockRelationQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = brq.Limit(2).IDs(setContextOp(ctx, brq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{blockrelation.Label}
	default:
		err = &NotSingularError{blockrelation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (brq *BlockRelationQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := brq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BlockRelations.
func (brq *BlockRelationQuery) All(ctx context.Context) ([]*BlockRelation, error) {
	ctx = setContextOp(ctx, brq.ctx, ent.OpQueryAll)
	if err := brq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BlockRelation, *BlockRelationQuery]()
	return withInterceptors[[]*BlockRelation](ctx, brq, qr, brq.inters)
}

// AllX is like All, but panics if an error occurs.
func (brq *BlockRelationQuery) AllX(ctx context.Context) []*BlockRelation {
	nodes, err := brq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BlockRelation IDs.
func (brq *BlockRelationQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if brq.ctx.Unique == nil && brq.path != nil {
		brq.Unique(true)
	}
	ctx = setContextOp(ctx, brq.ctx, ent.OpQueryIDs)
	if err = brq.Select(blockrelation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (brq *BlockRelationQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := brq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (brq *BlockRelationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, brq.ctx, ent.OpQueryCount)
	if err := brq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, brq, querierCount[*BlockRelationQuery](), brq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (brq *BlockRelationQuery) CountX(ctx context.Context) int {
	count, err := brq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (brq *BlockRelationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, brq.ctx, ent.OpQueryExist)
	switch _, err := brq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (brq *BlockRelationQuery) ExistX(ctx context.Context) bool {
	exist, err := brq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BlockRelationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (brq *BlockRelationQuery) Clone() *BlockRelationQuery {
	if brq == nil {
		return nil
	}
	return &BlockRelationQuery{
		config:     brq.config,
		ctx:        brq.ctx.Clone(),
		order:      append([]blockrelation.OrderOption{}, brq.order...),
		inters:     append([]Interceptor{}, brq.inters...),
		predicates: append([]predicate.BlockRelation{}, brq.predicates...),
		withFrom:   brq.withFrom.Clone(),
		withTo:     brq.withTo.Clone(),
		// clone intermediate query.
		sql:  brq.sql.Clone(),
		path: brq.path,
	}
}

// WithFrom tells the query-builder to eager-load the nodes that are connected to
// the "from" edge. The optional arguments are used to configure the query builder of the edge.
func (brq *BlockRelationQuery) WithFrom(opts ...func(*UserQuery)) *BlockRelationQuery {
	query := (&UserClient{config: brq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	brq.withFrom = query
	return brq
}

// WithTo tells the query-builder to eager-load the nodes that are connected to
// the "to" edge. The optional arguments are used to configure the query builder of the edge.
func (brq *BlockRelationQuery) WithTo(opts ...func(*UserQuery)) *BlockRelationQuery {
	query := (&UserClient{config: brq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	brq.withTo = query
	return brq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BlockRelation.Query().
//		GroupBy(blockrelation.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (brq *BlockRelationQuery) GroupBy(field string, fields ...string) *BlockRelationGroupBy {
	brq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BlockRelationGroupBy{build: brq}
	grbuild.flds = &brq.ctx.Fields
	grbuild.label = blockrelation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.BlockRelation.Query().
//		Select(blockrelation.FieldCreatedAt).
//		Scan(ctx, &v)
func (brq *BlockRelationQuery) Select(fields ...string) *BlockRelationSelect {
	brq.ctx.Fields = append(brq.ctx.Fields, fields...)
	sbuild := &BlockRelationSelect{BlockRelationQuery: brq}
	sbuild.label = blockrelation.Label
	sbuild.flds, sbuild.scan = &brq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BlockRelationSelect configured with the given aggregations.
func (brq *BlockRelationQuery) Aggregate(fns ...AggregateFunc) *BlockRelationSelect {
	return brq.Select().Aggregate(fns...)
}

func (brq *BlockRelationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range brq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, brq); err != nil {
				return err
			}
		}
	}
	for _, f := range brq.ctx.Fields {
		if !blockrelation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if brq.path != nil {
		prev, err := brq.path(ctx)
		if err != nil {
			return err
		}
		brq.sql = prev
	}
	return nil
}

func (brq *BlockRelationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BlockRelation, error) {
	var (
		nodes       = []*BlockRelation{}
		withFKs     = brq.withFKs
		_spec       = brq.querySpec()
		loadedTypes = [2]bool{
			brq.withFrom != nil,
			brq.withTo != nil,
		}
	)
	if brq.withFrom != nil || brq.withTo != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, blockrelation.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BlockRelation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BlockRelation{config: brq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, brq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := brq.withFrom; query != nil {
		if err := brq.loadFrom(ctx, query, nodes, nil,
			func(n *BlockRelation, e *User) { n.Edges.From = e }); err != nil {
			return nil, err
		}
	}
	if query := brq.withTo; query != nil {
		if err := brq.loadTo(ctx, query, nodes, nil,
			func(n *BlockRelation, e *User) { n.Edges.To = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (brq *BlockRelationQuery) loadFrom(ctx context.Context, query *UserQuery, nodes []*BlockRelation, init func(*BlockRelation), assign func(*BlockRelation, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*BlockRelation)
	for i := range nodes {
		if nodes[i].user_blocking == nil {
			continue
		}
		fk := *nodes[i].user_blocking
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_blocking" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (brq *BlockRelationQuery) loadTo(ctx context.Context, query *UserQuery, nodes []*BlockRelation, init func(*BlockRelation), assign func(*BlockRelation, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*BlockRelation)
	for i := range nodes {
		if nodes[i].user_blocked_by == nil {
			continue
		}
		fk := *nodes[i].user_blocked_by
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_blocked_by" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (brq *BlockRelationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := brq.querySpec()
	_spec.Node.Columns = brq.ctx.Fields
	if len(brq.ctx.Fields) > 0 {
		_spec.Unique = brq.ctx.Unique != nil && *brq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, brq.driver, _spec)
}

func (brq *BlockRelationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(blockrelation.Table, blockrelation.Columns, sqlgraph.NewFieldSpec(blockrelation.FieldID, field.TypeUUID))
	_spec.From = brq.sql
	if unique := brq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if brq.path != nil {
		_spec.Unique = true
	}
	if fields := brq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, blockrelation.FieldID)
		for i := range fields {
			if fields[i] != blockrelation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := brq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := brq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := brq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := brq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (brq *BlockRelationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(brq.driver.Dialect())
	t1 := builder.Table(blockrelation.Table)
	columns := brq.ctx.Fields
	if len(columns) == 0 {
		columns = blockrelation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if brq.sql != nil {
		selector = brq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if brq.ctx.Unique != nil && *brq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range brq.predicates {
		p(selector)
	}
	for _, p := range brq.order {
		p(selector)
	}
	if offset := brq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := brq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BlockRelationGroupBy is the group-by builder for BlockRelation entities.
type BlockRelationGroupBy struct {
	selector
	build *BlockRelationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (brgb *BlockRelationGroupBy) Aggregate(fns ...AggregateFunc) *BlockRelationGroupBy {
	brgb.fns = append(brgb.fns, fns...)
	return brgb
}

// Scan applies the selector query and scans the result into the given value.
func (brgb *BlockRelationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, brgb.build.ctx, ent.OpQueryGroupBy)
	if err := brgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BlockRelationQuery, *BlockRelationGroupBy](ctx, brgb.build, brgb, brgb.build.inters, v)
}

func (brgb *BlockRelationGroupBy) sqlScan(ctx context.Context, root *BlockRelationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(brgb.fns))
	for _, fn := range brgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*brgb.flds)+len(brgb.fns))
		for _, f := range *brgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*brgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := brgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BlockRelationSelect is the builder for selecting fields of BlockRelation entities.
type BlockRelationSelect struct {
	*BlockRelationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (brs *BlockRelationSelect) Aggregate(fns ...AggregateFunc) *BlockRelationSelect {
	brs.fns = append(brs.fns, fns...)
	return brs
}

// Scan applies the selector query and scans the result into the given value.
func (brs *BlockRelationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, brs.ctx, ent.OpQuerySelect)
	if err := brs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BlockRelationQuery, *BlockRelationSelect](ctx, brs.BlockRelationQuery, brs, brs.inters, v)
}

func (brs *BlockRelationSelect) sqlScan(ctx context.Context, root *BlockRelationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(brs.fns))
	for _, fn := range brs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*brs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := brs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
