// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aki-13627/animalia/backend-go/ent/devicetoken"
	"github.com/aki-13627/animalia/backend-go/ent/user"
	"github.com/google/uuid"
)

// DeviceTokenCreate is the builder for creating a DeviceToken entity.
type DeviceTokenCreate struct {
	config
	mutation *DeviceTokenMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (dtc *DeviceTokenCreate) SetUserID(u uuid.UUID) *DeviceTokenCreate {
	dtc.mutation.SetUserID(u)
	return dtc
}

// SetDeviceID sets the "device_id" field.
func (dtc *DeviceTokenCreate) SetDeviceID(s string) *DeviceTokenCreate {
	dtc.mutation.SetDeviceID(s)
	return dtc
}

// SetToken sets the "token" field.
func (dtc *DeviceTokenCreate) SetToken(s string) *DeviceTokenCreate {
	dtc.mutation.SetToken(s)
	return dtc
}

// SetPlatform sets the "platform" field.
func (dtc *DeviceTokenCreate) SetPlatform(s string) *DeviceTokenCreate {
	dtc.mutation.SetPlatform(s)
	return dtc
}

// SetCreatedAt sets the "created_at" field.
func (dtc *DeviceTokenCreate) SetCreatedAt(t time.Time) *DeviceTokenCreate {
	dtc.mutation.SetCreatedAt(t)
	return dtc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (dtc *DeviceTokenCreate) SetNillableCreatedAt(t *time.Time) *DeviceTokenCreate {
	if t != nil {
		dtc.SetCreatedAt(*t)
	}
	return dtc
}

// SetUpdatedAt sets the "updated_at" field.
func (dtc *DeviceTokenCreate) SetUpdatedAt(t time.Time) *DeviceTokenCreate {
	dtc.mutation.SetUpdatedAt(t)
	return dtc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (dtc *DeviceTokenCreate) SetNillableUpdatedAt(t *time.Time) *DeviceTokenCreate {
	if t != nil {
		dtc.SetUpdatedAt(*t)
	}
	return dtc
}

// SetID sets the "id" field.
func (dtc *DeviceTokenCreate) SetID(u uuid.UUID) *DeviceTokenCreate {
	dtc.mutation.SetID(u)
	return dtc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (dtc *DeviceTokenCreate) SetNillableID(u *uuid.UUID) *DeviceTokenCreate {
	if u != nil {
		dtc.SetID(*u)
	}
	return dtc
}

// SetUser sets the "user" edge to the User entity.
func (dtc *DeviceTokenCreate) SetUser(u *User) *DeviceTokenCreate {
	return dtc.SetUserID(u.ID)
}

// Mutation returns the DeviceTokenMutation object of the builder.
func (dtc *DeviceTokenCreate) Mutation() *DeviceTokenMutation {
	return dtc.mutation
}

// Save creates the DeviceToken in the database.
func (dtc *DeviceTokenCreate) Save(ctx context.Context) (*DeviceToken, error) {
	dtc.defaults()
	return withHooks(ctx, dtc.sqlSave, dtc.mutation, dtc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dtc *DeviceTokenCreate) SaveX(ctx context.Context) *DeviceToken {
	v, err := dtc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dtc *DeviceTokenCreate) Exec(ctx context.Context) error {
	_, err := dtc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dtc *DeviceTokenCreate) ExecX(ctx context.Context) {
	if err := dtc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dtc *DeviceTokenCreate) defaults() {
	if _, ok := dtc.mutation.CreatedAt(); !ok {
		v := devicetoken.DefaultCreatedAt()
		dtc.mutation.SetCreatedAt(v)
	}
	if _, ok := dtc.mutation.UpdatedAt(); !ok {
		v := devicetoken.DefaultUpdatedAt()
		dtc.mutation.SetUpdatedAt(v)
	}
	if _, ok := dtc.mutation.ID(); !ok {
		v := devicetoken.DefaultID()
		dtc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dtc *DeviceTokenCreate) check() error {
	if _, ok := dtc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "DeviceToken.user_id"`)}
	}
	if _, ok := dtc.mutation.DeviceID(); !ok {
		return &ValidationError{Name: "device_id", err: errors.New(`ent: missing required field "DeviceToken.device_id"`)}
	}
	if v, ok := dtc.mutation.DeviceID(); ok {
		if err := devicetoken.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "DeviceToken.device_id": %w`, err)}
		}
	}
	if _, ok := dtc.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "DeviceToken.token"`)}
	}
	if v, ok := dtc.mutation.Token(); ok {
		if err := devicetoken.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "DeviceToken.token": %w`, err)}
		}
	}
	if _, ok := dtc.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "DeviceToken.platform"`)}
	}
	if v, ok := dtc.mutation.Platform(); ok {
		if err := devicetoken.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "DeviceToken.platform": %w`, err)}
		}
	}
	if _, ok := dtc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DeviceToken.created_at"`)}
	}
	if _, ok := dtc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DeviceToken.updated_at"`)}
	}
	if len(dtc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "DeviceToken.user"`)}
	}
	return nil
}

func (dtc *DeviceTokenCreate) sqlSave(ctx context.Context) (*DeviceToken, error) {
	if err := dtc.check(); err != nil {
		return nil, err
	}
	_node, _spec := dtc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dtc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	dtc.mutation.id = &_node.ID
	dtc.mutation.done = true
	return _node, nil
}

func (dtc *DeviceTokenCreate) createSpec() (*DeviceToken, *sqlgraph.CreateSpec) {
	var (
		_node = &DeviceToken{config: dtc.config}
		_spec = sqlgraph.NewCreateSpec(devicetoken.Table, sqlgraph.NewFieldSpec(devicetoken.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = dtc.conflict
	if id, ok := dtc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := dtc.mutation.DeviceID(); ok {
		_spec.SetField(devicetoken.FieldDeviceID, field.TypeString, value)
		_node.DeviceID = value
	}
	if value, ok := dtc.mutation.Token(); ok {
		_spec.SetField(devicetoken.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := dtc.mutation.Platform(); ok {
		_spec.SetField(devicetoken.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := dtc.mutation.CreatedAt(); ok {
		_spec.SetField(devicetoken.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := dtc.mutation.UpdatedAt(); ok {
		_spec.SetField(devicetoken.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := dtc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   devicetoken.UserTable,
			Columns: []string{devicetoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DeviceToken.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeviceTokenUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (dtc *DeviceTokenCreate) OnConflict(opts ...sql.ConflictOption) *DeviceTokenUpsertOne {
	dtc.conflict = opts
	return &DeviceTokenUpsertOne{
		create: dtc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DeviceToken.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (dtc *DeviceTokenCreate) OnConflictColumns(columns ...string) *DeviceTokenUpsertOne {
	dtc.conflict = append(dtc.conflict, sql.ConflictColumns(columns...))
	return &DeviceTokenUpsertOne{
		create: dtc,
	}
}

type (
	// DeviceTokenUpsertOne is the builder for "upsert"-ing
	//  one DeviceToken node.
	DeviceTokenUpsertOne struct {
		create *DeviceTokenCreate
	}

	// DeviceTokenUpsert is the "OnConflict" setter.
	DeviceTokenUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *DeviceTokenUpsert) SetUserID(v uuid.UUID) *DeviceTokenUpsert {
	u.Set(devicetoken.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DeviceTokenUpsert) UpdateUserID() *DeviceTokenUpsert {
	u.SetExcluded(devicetoken.FieldUserID)
	return u
}

// SetDeviceID sets the "device_id" field.
func (u *DeviceTokenUpsert) SetDeviceID(v string) *DeviceTokenUpsert {
	u.Set(devicetoken.FieldDeviceID, v)
	return u
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *DeviceTokenUpsert) UpdateDeviceID() *DeviceTokenUpsert {
	u.SetExcluded(devicetoken.FieldDeviceID)
	return u
}

// SetToken sets the "token" field.
func (u *DeviceTokenUpsert) SetToken(v string) *DeviceTokenUpsert {
	u.Set(devicetoken.FieldToken, v)
	return u
}

// UpdateToken sets the "token" field to the value that was provided on create.
func (u *DeviceTokenUpsert) UpdateToken() *DeviceTokenUpsert {
	u.SetExcluded(devicetoken.FieldToken)
	return u
}

// SetPlatform sets the "platform" field.
func (u *DeviceTokenUpsert) SetPlatform(v string) *DeviceTokenUpsert {
	u.Set(devicetoken.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *DeviceTokenUpsert) UpdatePlatform() *DeviceTokenUpsert {
	u.SetExcluded(devicetoken.FieldPlatform)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *DeviceTokenUpsert) SetCreatedAt(v time.Time) *DeviceTokenUpsert {
	u.Set(devicetoken.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *DeviceTokenUpsert) UpdateCreatedAt() *DeviceTokenUpsert {
	u.SetExcluded(devicetoken.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DeviceTokenUpsert) SetUpdatedAt(v time.Time) *DeviceTokenUpsert {
	u.Set(devicetoken.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DeviceTokenUpsert) UpdateUpdatedAt() *DeviceTokenUpsert {
	u.SetExcluded(devicetoken.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.DeviceToken.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(devicetoken.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DeviceTokenUpsertOne) UpdateNewValues() *DeviceTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(devicetoken.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DeviceToken.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DeviceTokenUpsertOne) Ignore() *DeviceTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeviceTokenUpsertOne) DoNothing() *DeviceTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeviceTokenCreate.OnConflict
// documentation for more info.
func (u *DeviceTokenUpsertOne) Update(set func(*DeviceTokenUpsert)) *DeviceTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeviceTokenUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *DeviceTokenUpsertOne) SetUserID(v uuid.UUID) *DeviceTokenUpsertOne {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DeviceTokenUpsertOne) UpdateUserID() *DeviceTokenUpsertOne {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.UpdateUserID()
	})
}

// SetDeviceID sets the "device_id" field.
func (u *DeviceTokenUpsertOne) SetDeviceID(v string) *DeviceTokenUpsertOne {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.SetDeviceID(v)
	})
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *DeviceTokenUpsertOne) UpdateDeviceID() *DeviceTokenUpsertOne {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.UpdateDeviceID()
	})
}

// SetToken sets the "token" field.
func (u *DeviceTokenUpsertOne) SetToken(v string) *DeviceTokenUpsertOne {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.SetToken(v)
	})
}

// UpdateToken sets the "token" field to the value that was provided on create.
func (u *DeviceTokenUpsertOne) UpdateToken() *DeviceTokenUpsertOne {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.UpdateToken()
	})
}

// SetPlatform sets the "platform" field.
func (u *DeviceTokenUpsertOne) SetPlatform(v string) *DeviceTokenUpsertOne {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *DeviceTokenUpsertOne) UpdatePlatform() *DeviceTokenUpsertOne {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.UpdatePlatform()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *DeviceTokenUpsertOne) SetCreatedAt(v time.Time) *DeviceTokenUpsertOne {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *DeviceTokenUpsertOne) UpdateCreatedAt() *DeviceTokenUpsertOne {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DeviceTokenUpsertOne) SetUpdatedAt(v time.Time) *DeviceTokenUpsertOne {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DeviceTokenUpsertOne) UpdateUpdatedAt() *DeviceTokenUpsertOne {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DeviceTokenUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeviceTokenCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeviceTokenUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DeviceTokenUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DeviceTokenUpsertOne.ID is not supported by MySQL driver. Use DeviceTokenUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DeviceTokenUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DeviceTokenCreateBulk is the builder for creating many DeviceToken entities in bulk.
type DeviceTokenCreateBulk struct {
	config
	err      error
	builders []*DeviceTokenCreate
	conflict []sql.ConflictOption
}

// Save creates the DeviceToken entities in the database.
func (dtcb *DeviceTokenCreateBulk) Save(ctx context.Context) ([]*DeviceToken, error) {
	if dtcb.err != nil {
		return nil, dtcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(dtcb.builders))
	nodes := make([]*DeviceToken, len(dtcb.builders))
	mutators := make([]Mutator, len(dtcb.builders))
	for i := range dtcb.builders {
		func(i int, root context.Context) {
			builder := dtcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeviceTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dtcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = dtcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dtcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dtcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dtcb *DeviceTokenCreateBulk) SaveX(ctx context.Context) []*DeviceToken {
	v, err := dtcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dtcb *DeviceTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := dtcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dtcb *DeviceTokenCreateBulk) ExecX(ctx context.Context) {
	if err := dtcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DeviceToken.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeviceTokenUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (dtcb *DeviceTokenCreateBulk) OnConflict(opts ...sql.ConflictOption) *DeviceTokenUpsertBulk {
	dtcb.conflict = opts
	return &DeviceTokenUpsertBulk{
		create: dtcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DeviceToken.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (dtcb *DeviceTokenCreateBulk) OnConflictColumns(columns ...string) *DeviceTokenUpsertBulk {
	dtcb.conflict = append(dtcb.conflict, sql.ConflictColumns(columns...))
	return &DeviceTokenUpsertBulk{
		create: dtcb,
	}
}

// DeviceTokenUpsertBulk is the builder for "upsert"-ing
// a bulk of DeviceToken nodes.
type DeviceTokenUpsertBulk struct {
	create *DeviceTokenCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DeviceToken.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(devicetoken.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DeviceTokenUpsertBulk) UpdateNewValues() *DeviceTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(devicetoken.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DeviceToken.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DeviceTokenUpsertBulk) Ignore() *DeviceTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeviceTokenUpsertBulk) DoNothing() *DeviceTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeviceTokenCreateBulk.OnConflict
// documentation for more info.
func (u *DeviceTokenUpsertBulk) Update(set func(*DeviceTokenUpsert)) *DeviceTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeviceTokenUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *DeviceTokenUpsertBulk) SetUserID(v uuid.UUID) *DeviceTokenUpsertBulk {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DeviceTokenUpsertBulk) UpdateUserID() *DeviceTokenUpsertBulk {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.UpdateUserID()
	})
}

// SetDeviceID sets the "device_id" field.
func (u *DeviceTokenUpsertBulk) SetDeviceID(v string) *DeviceTokenUpsertBulk {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.SetDeviceID(v)
	})
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *DeviceTokenUpsertBulk) UpdateDeviceID() *DeviceTokenUpsertBulk {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.UpdateDeviceID()
	})
}

// SetToken sets the "token" field.
func (u *DeviceTokenUpsertBulk) SetToken(v string) *DeviceTokenUpsertBulk {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.SetToken(v)
	})
}

// UpdateToken sets the "token" field to the value that was provided on create.
func (u *DeviceTokenUpsertBulk) UpdateToken() *DeviceTokenUpsertBulk {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.UpdateToken()
	})
}

// SetPlatform sets the "platform" field.
func (u *DeviceTokenUpsertBulk) SetPlatform(v string) *DeviceTokenUpsertBulk {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *DeviceTokenUpsertBulk) UpdatePlatform() *DeviceTokenUpsertBulk {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.UpdatePlatform()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *DeviceTokenUpsertBulk) SetCreatedAt(v time.Time) *DeviceTokenUpsertBulk {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *DeviceTokenUpsertBulk) UpdateCreatedAt() *DeviceTokenUpsertBulk {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DeviceTokenUpsertBulk) SetUpdatedAt(v time.Time) *DeviceTokenUpsertBulk {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DeviceTokenUpsertBulk) UpdateUpdatedAt() *DeviceTokenUpsertBulk {
	return u.Update(func(s *DeviceTokenUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DeviceTokenUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DeviceTokenCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeviceTokenCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeviceTokenUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
